In [426]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [427]:
df = pd.read_csv(r'C:\thesis\datasets.csv')
df.head(10)

,student_id,age,sex,course,yr_level,socioeconomic_stat,fam_support,working_stud,scholar,personality_type,...,tablet,wifi,prepaid-wifi,cellular_data,hotspot,vhigh_speed,high_speed,moderate_speed,light_speed,GPA
0,2021-01592,19.0,F,CD,2,low,yes,no,yes,ISTJ,...,never,never,always,always,sometimes,always,always,sometimes,sometimes,1.5588
1,2021-02910,19.0,F,CD,2,lower middle,yes,no,no,ESFJ,...,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.3824
2,2021-02862,19.0,F,CD,2,low,yes,no,no,ENTP,...,an,always,never,always,sometimes,sometimes,always,sometimes,sometimes,1.5882
3,2021-02890,19.0,F,CD,2,lower middle,yes,yes,no,ESFJ,...,never,always,sometimes,never,sometimes,sometimes,sometimes,always,sometimes,1.5000
4,2020-04136,20.0,F,CD,2,low,yes,no,no,ISFJ,...,sometimes,sometimes,never,sometimes,sometimes,never,sometimes,sometimes,always,1.4347
5,2020-02817,21.0,F,CD,2,low,yes,no,no,ENFJ,...,sometimes,always,never,always,never,Sometimes,sometimes,sometimes,always,2.2500
6,2021-02734,19.0,F,CD,2,low,yes,no,no,ISTJ,...,never,sometimes,never,sometimes,never,never,never,sometimes,never,1.5000
7,2021-01674,21.0,F,CD,2,low,no,yes,no,INFJ,...,never,always,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.5294
8,2021-01715,19.0,F,CD,2,low,yes,no,no,ISFP,...,never,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.7206
9,2021-01769,19.0,F,CD,2,low,yes,no,no,ISFJ,...,never,never,never,always,never,never,never,sometimes,always,1.5000

In [428]:
df.columns

Index(['student_id', 'age', 'sex', 'course', 'yr_level', 'socioeconomic_stat',
       'fam_support', 'working_stud', 'scholar', 'personality_type', 'TM1',
       'TM2', 'TM3', 'TM4', 'TM5', 'TM6', 'TM7', 'CAP1', 'CAP2', 'CAP3',
       'CAP4', 'GSS1', 'GSS2', 'GSS3', 'GSS4', 'GSS5', 'GSS6', 'GSS7', 'EP1',
       'EP2', 'EP3', 'EP4', 'EP5', 'EP6', 'NT1', 'NT2', 'NT3', 'desktop',
       'laptop', 'mobile_phone', 'tablet', 'wifi', 'prepaid-wifi',
       'cellular_data', 'hotspot', 'vhigh_speed', 'high_speed',
       'moderate_speed', 'light_speed', 'GPA'],
      dtype='object')

# EXPLORING THE DATA

In [429]:
df.shape

(357, 50)

In [430]:
df.isnull().sum()

student_id             0
age                   11
sex                    6
course                 0
yr_level               0
socioeconomic_stat     0
fam_support            0
working_stud           0
scholar                0
personality_type      49
TM1                    0
TM2                    0
TM3                    0
TM4                    0
TM5                    0
TM6                    0
TM7                    0
CAP1                   0
CAP2                   0
CAP3                   1
CAP4                   0
GSS1                   0
GSS2                   0
GSS3                   0
GSS4                   0
GSS5                   0
GSS6                   0
GSS7                   0
EP1                    0
EP2                    0
EP3                    0
EP4                    0
EP5                    0
EP6                    0
NT1                    0
NT2                    0
NT3                    0
desktop                0
laptop                 0
mobile_phone           0
tablet                 0
wifi                   0
prepaid-wifi           0
cellular_data          0
hotspot                0
vhigh_speed            0
high_speed             0
moderate_speed         0
light_speed            0
GPA                    0
dtype: int64

In [431]:
df["age"].fillna(df["age"].mean(), inplace = True)
df.age.isna().sum()

0

In [432]:
df2 = df.fillna(method = 'ffill')
df2.isnull().sum()

student_id            0
age                   0
sex                   0
course                0
yr_level              0
socioeconomic_stat    0
fam_support           0
working_stud          0
scholar               0
personality_type      0
TM1                   0
TM2                   0
TM3                   0
TM4                   0
TM5                   0
TM6                   0
TM7                   0
CAP1                  0
CAP2                  0
CAP3                  0
CAP4                  0
GSS1                  0
GSS2                  0
GSS3                  0
GSS4                  0
GSS5                  0
GSS6                  0
GSS7                  0
EP1                   0
EP2                   0
EP3                   0
EP4                   0
EP5                   0
EP6                   0
NT1                   0
NT2                   0
NT3                   0
desktop               0
laptop                0
mobile_phone          0
tablet                0
wifi                  0
prepaid-wifi          0
cellular_data         0
hotspot               0
vhigh_speed           0
high_speed            0
moderate_speed        0
light_speed           0
GPA                   0
dtype: int64

In [433]:
df2.head(10)

,student_id,age,sex,course,yr_level,socioeconomic_stat,fam_support,working_stud,scholar,personality_type,...,tablet,wifi,prepaid-wifi,cellular_data,hotspot,vhigh_speed,high_speed,moderate_speed,light_speed,GPA
0,2021-01592,19.0,F,CD,2,low,yes,no,yes,ISTJ,...,never,never,always,always,sometimes,always,always,sometimes,sometimes,1.5588
1,2021-02910,19.0,F,CD,2,lower middle,yes,no,no,ESFJ,...,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.3824
2,2021-02862,19.0,F,CD,2,low,yes,no,no,ENTP,...,an,always,never,always,sometimes,sometimes,always,sometimes,sometimes,1.5882
3,2021-02890,19.0,F,CD,2,lower middle,yes,yes,no,ESFJ,...,never,always,sometimes,never,sometimes,sometimes,sometimes,always,sometimes,1.5000
4,2020-04136,20.0,F,CD,2,low,yes,no,no,ISFJ,...,sometimes,sometimes,never,sometimes,sometimes,never,sometimes,sometimes,always,1.4347
5,2020-02817,21.0,F,CD,2,low,yes,no,no,ENFJ,...,sometimes,always,never,always,never,Sometimes,sometimes,sometimes,always,2.2500
6,2021-02734,19.0,F,CD,2,low,yes,no,no,ISTJ,...,never,sometimes,never,sometimes,never,never,never,sometimes,never,1.5000
7,2021-01674,21.0,F,CD,2,low,no,yes,no,INFJ,...,never,always,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.5294
8,2021-01715,19.0,F,CD,2,low,yes,no,no,ISFP,...,never,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.7206
9,2021-01769,19.0,F,CD,2,low,yes,no,no,ISFJ,...,never,never,never,always,never,never,never,sometimes,always,1.5000

In [434]:
df2.isnull().sum().sum()

0

In [435]:
df2.course.unique()

array(['CD', 'IT', 'CS', 'SW'], dtype=object)

In [436]:
df2.fam_support.unique()

array(['yes', 'no'], dtype=object)

In [437]:
df2.sex.unique()

array(['F', 'M', 'M ', 'F '], dtype=object)

In [439]:
df2["sex"].replace("M ", "M", inplace = True )
df2["sex"].replace("F ", "F", inplace = True )
df2.sex.unique()

array(['F', 'M'], dtype=object)

In [440]:
df2.personality_type.unique()

array(['ISTJ', 'ESFJ', 'ENTP', 'ISFJ', 'ENFJ', 'INFJ', 'ISFP', 'INTJ',
       'ENTJ', 'ESTP', 'INFP', 'ESFP', 'ENFP', 'ISTP', 'ESTJ', 'INTP'],
      dtype=object)

In [441]:
df2.personality_type.unique()

array(['ISTJ', 'ESFJ', 'ENTP', 'ISFJ', 'ENFJ', 'INFJ', 'ISFP', 'INTJ',
       'ENTJ', 'ESTP', 'INFP', 'ESFP', 'ENFP', 'ISTP', 'ESTJ', 'INTP'],
      dtype=object)

### Transforming Catergorical data

In [442]:
df2.columns

Index(['student_id', 'age', 'sex', 'course', 'yr_level', 'socioeconomic_stat',
       'fam_support', 'working_stud', 'scholar', 'personality_type', 'TM1',
       'TM2', 'TM3', 'TM4', 'TM5', 'TM6', 'TM7', 'CAP1', 'CAP2', 'CAP3',
       'CAP4', 'GSS1', 'GSS2', 'GSS3', 'GSS4', 'GSS5', 'GSS6', 'GSS7', 'EP1',
       'EP2', 'EP3', 'EP4', 'EP5', 'EP6', 'NT1', 'NT2', 'NT3', 'desktop',
       'laptop', 'mobile_phone', 'tablet', 'wifi', 'prepaid-wifi',
       'cellular_data', 'hotspot', 'vhigh_speed', 'high_speed',
       'moderate_speed', 'light_speed', 'GPA'],
      dtype='object')

In [443]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [444]:
#list = ['sex', 'course']

#for i in list:
  df2[i] = encoder.fit_transform(df[i])

In [445]:
df2.head(10)

,student_id,age,sex,course,yr_level,socioeconomic_stat,fam_support,working_stud,scholar,personality_type,...,tablet,wifi,prepaid-wifi,cellular_data,hotspot,vhigh_speed,high_speed,moderate_speed,light_speed,GPA
0,2021-01592,19.0,F,CD,2,low,yes,no,yes,ISTJ,...,never,never,always,always,sometimes,always,always,sometimes,sometimes,1.5588
1,2021-02910,19.0,F,CD,2,lower middle,yes,no,no,ESFJ,...,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.3824
2,2021-02862,19.0,F,CD,2,low,yes,no,no,ENTP,...,an,always,never,always,sometimes,sometimes,always,sometimes,sometimes,1.5882
3,2021-02890,19.0,F,CD,2,lower middle,yes,yes,no,ESFJ,...,never,always,sometimes,never,sometimes,sometimes,sometimes,always,sometimes,1.5000
4,2020-04136,20.0,F,CD,2,low,yes,no,no,ISFJ,...,sometimes,sometimes,never,sometimes,sometimes,never,sometimes,sometimes,always,1.4347
5,2020-02817,21.0,F,CD,2,low,yes,no,no,ENFJ,...,sometimes,always,never,always,never,Sometimes,sometimes,sometimes,always,2.2500
6,2021-02734,19.0,F,CD,2,low,yes,no,no,ISTJ,...,never,sometimes,never,sometimes,never,never,never,sometimes,never,1.5000
7,2021-01674,21.0,F,CD,2,low,no,yes,no,INFJ,...,never,always,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.5294
8,2021-01715,19.0,F,CD,2,low,yes,no,no,ISFP,...,never,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,sometimes,1.7206
9,2021-01769,19.0,F,CD,2,low,yes,no,no,ISFJ,...,never,never,never,always,never,never,never,sometimes,always,1.5000

0=CD, 1=CS, 2=IT, 3=SW,
0=F, 1=M

In [446]:
df2.course.unique()

array(['CD', 'IT', 'CS', 'SW'], dtype=object)

In [447]:
list = ['socioeconomic_stat',
       'fam_support', 'working_stud', 'scholar', 'TM1',
       'TM2', 'TM3', 'TM4', 'TM5', 'TM6', 'TM7', 'CAP1', 'CAP2', 'CAP3',
       'CAP4', 'GSS1', 'GSS2', 'GSS3', 'GSS4', 'GSS5', 'GSS6', 'GSS7', 'EP1',
       'EP2', 'EP3', 'EP4', 'EP5', 'EP6', 'NT1', 'NT2', 'NT3', 'desktop',
       'laptop', 'mobile_phone', 'tablet', 'wifi', 'prepaid-wifi',
       'cellular_data', 'hotspot', 'vhigh_speed', 'high_speed',
       'moderate_speed', 'light_speed']

for i in list:
  df2[i] = encoder.fit_transform(df[i])

In [448]:
df2.head()

,student_id,age,sex,course,yr_level,socioeconomic_stat,fam_support,working_stud,scholar,personality_type,...,tablet,wifi,prepaid-wifi,cellular_data,hotspot,vhigh_speed,high_speed,moderate_speed,light_speed,GPA
0,2021-01592,19.0,F,CD,2,1,1,0,1,ISTJ,...,2,1,1,0,2,1,0,3,2,1.5588
1,2021-02910,19.0,F,CD,2,4,1,0,0,ESFJ,...,3,2,3,2,2,3,3,3,2,1.3824
2,2021-02862,19.0,F,CD,2,1,1,0,0,ENTP,...,1,0,2,0,2,3,0,3,2,1.5882
3,2021-02890,19.0,F,CD,2,4,1,1,0,ESFJ,...,2,0,3,1,2,3,3,0,2,1.5000
4,2020-04136,20.0,F,CD,2,1,1,0,0,ISFJ,...,3,2,2,2,2,2,3,3,0,1.4347

In [449]:
df2['personality_type'].unique()

array(['ISTJ', 'ESFJ', 'ENTP', 'ISFJ', 'ENFJ', 'INFJ', 'ISFP', 'INTJ',
       'ENTJ', 'ESTP', 'INFP', 'ESFP', 'ENFP', 'ISTP', 'ESTJ', 'INTP'],
      dtype=object)

In [450]:
df2['personality_type'].value_counts()

ENFP    43
ISTJ    39
INTJ    38
ESFJ    36
ENFJ    28
INFJ    28
ISFP    27
ISFJ    26
INFP    19
ESTP    14
ESTJ    14
ISTP    13
ESFP    12
ENTJ     9
ENTP     6
INTP     5
Name: personality_type, dtype: int64

In [458]:
#create pivot table
df_pivot = pd.pivot_table(df2, values='fam_support', index='sex', columns='personality_type',
                          aggfunc='count')
df_pivot

personality_type,ENFJ,ENFP,ENTJ,ENTP,ESFJ,ESFP,ESTJ,ESTP,INFJ,INFP,INTJ,INTP,ISFJ,ISFP,ISTJ,ISTP
sex,,,,,,,,,,,,,,,,
F,17,17,5,3,20,9,4,6,25,17,18,2,16,14,21,4
M,11,26,4,3,16,3,10,8,3,2,20,3,10,13,18,9

interpretation :
                This Pivot Table counts the number of students with family support in respect with their personality and Sex.

In [452]:
df2['sex'].unique()

array(['F', 'M'], dtype=object)

In [425]:
df2.fam_support.unique()

array([1, 0])

In [460]:
df2.cellular_data.unique()

array([0, 2, 1])